### PR TITLE
Add wrappers for rest calls and use in functions

### LINKED ISSUE #58: Wrap rest calls in individual functions
Wrap the rest calls in individual functions. Use these in the functions that need to do rest calls.

Create wrappers for:
- [ ] restGET
- [ ] restPOST
- [ ] restPUT
- [ ] restDELETE

### PR DESCRIPTION
**Pull request by Aryllen**
Fixes #58.

The REST calls (get, put, post, and delete) all have their own function wrappers. Exported them because they might be handy in the future. Changed the existing functions to use these wrappers instead of making the calls themselves.

Need to verify that the functions are still working as they should. Will check tomorrow morning, after  not looking at it for awhile. @philerooski or @karawoo, if you have time, it would be great if you could check that these still work for you. Since they don't have tests, yet, I am nervous to update.

### CODE REVIEW

**Review by karawoo — APPROVED** [review]
I tried this out with the stopadforms shiny app and everything worked normally 👍

**Comment by philerooski** [comment]
One thing that I would change (but is entirely optional) is to replace the full URI with just the endpoint. Methods like syn$restGET et al already know where to find Synapse.

So
```
syn$restGET("https://repo-prod.prod.sagebase.org/repo/v1/form/group/{group}/acl")
```
can be written
```
syn$restGET("/form/group/{group}/acl")
```

**Comment by karawoo** [comment]
oh nice, I didn't know that @philerooski

**Comment by Aryllen** [comment]
I didn't know that either, @philerooski. That is handy. I will do that. Does this also allow for changing where the synapseclient is looking versus always looking at the production version?

Thank you, @karawoo!

I noticed that I was about to have a bug in one of the functions (that stopadforms doesn't use). Fixing that by putting some defaults for the body param. Will update to endpoints, as well.

**Comment by philerooski** [comment]
@Aryllen It defaults to https://repo-prod.prod.sagebase.org/repo/v1.

e.g.
```
syn$restGET("https://repo-prod.prod.sagebase.org/repo/v1/entity/syn1234567")
```
is equivalent to 
```
syn$restGET("/entity/syn1234567", endpoint = "https://repo-prod.prod.sagebase.org/repo/v1")
```
is equivalent to
```
syn$restGET("/entity/syn1234567")
```

**Comment by philerooski** [comment]
(My networking terminology is a little rusty. I've probably confused what is a URI and what is an endpoint in my original comment).

**Comment by Aryllen** [comment]
@philerooski, thanks for the info! I am wondering if I should add the ability to change the endpoint, as well. That might be useful in the future. I think that would be a different PR, though, since I am attempting to get this done ASAP for today's code review meeting. Haha.

**Comment by Aryllen** [comment]
So I removed the endpoints and tested on a test version of stopadforms. It didn't work. XD I don't remember if I tested it locally first (I have tested it so much today that I can't remember if I tested it after that commit, haha). But anywho, I reverted that one commit and it seems to be working, again. Tested locally and on a test version of stopadforms.

**Pull request merged**
